[package]
name = "shortguid"
version = "0.1.0"
edition = "2021"
license = "EUPL-1.2"
description = "Short URL-safe Base64 encoded UUIDs"
repository = "https://github.com/nyris/shortguid-rs"
authors = ["Markus Mayer <m.mayer@nyris.io>"]
readme = "README.md"
rust-version = "1.67.1"

[dependencies]
base64 = "0.21.0"
uuid = "1.3.0"
