[package]
name = "shortguid"
version = "0.4.0-unstable"
edition = "2021"
license = "EUPL-1.2"
description = "Short URL-safe Base64 encoded UUIDs"
repository = "https://github.com/nyris/shortguid-rs"
authors = ["Markus Mayer <m.mayer@nyris.io>"]
readme = "README.md"
rust-version = "1.67.1"

[dependencies]
arbitrary = { version = "1.3.0", optional = true }
base64 = "0.21.0"
uuid = "1.3.0"
clap = "4.2.4"

[features]
default = ["random"]
arbitrary = ["uuid/arbitrary", "arbitrary/derive"]
random = ["uuid/v4"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
